REFRESH_CACHE_KAFKA_KEY = "refresh-cache"
REFRESH_CACHE_KAFKA_MODE_PAYLOAD_PICKER = "payload-picker"
FIREBASE_SUBSCRIPTION_UPDATE_KAFKA_KEY = "firebase-subscription-update"
FIREBASE_SUBSCRIPTON_TOPIC_MODE_ADD = "add"
FIREBASE_SUBSCRIPTON_TOPIC_MODE_REMOVE = "remove"
DOT_SEPARATOR = '.'
COMMA_SEPARATOR = ','
